# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      skhabibullin@yandex.ru
    on_success: never # default: change
    on_failure: always # defa,ult: always

# код взят с сайта https://codecov.io/ для чего он нужен нихрена не понятно
env:
  global:
    - CODECOV_TOKEN="78b893ef-f69f-4bdf-8e64-e56b5fa74a79"