 select * from users;
 create table state( id serial primary key, name varchar(2000), item_id int references item(id) );
 create table category( id serial primary key, name varchar(2000), item_id int references item(id) );
 create table comments( id serial primary key, name varchar(2000), item_id int references item(id) );
 create table item( id serial primary key, name varchar(2000), users_id int references users(id) );
 create table rules_role( id serial primary key, relus_id int references rules(id), role_id int references role(id) );
 create table rules( id serial primary key, name varchar(2000) );
 create table rules( id serial primary key, name varchar(2000), );
 create table role( id serial primary key, name varchar(2000), users_id int references users(id) );
 create table users( id serial primary key, name varchar(2000) );